name: Deploy to S3 + CloudFront

on:
  push:
    branches:
      - master
    paths:
      - 'front/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[up]')"
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        working-directory: ./front
        run: npm install
        
      - name: Build
        working-directory: ./front
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Deploy to S3 (optimized)
        run: |
          # size-only 옵션으로 크기가 다른 파일만 업로드
          # exclude와 include를 사용하여 PDF는 별도 처리
          aws s3 sync front/dist/ s3://${{ secrets.S3_BUCKET_NAME }} \
            --delete \
            --exclude "pdf/*" \
            --size-only
            
          # PDF 파일은 크기와 타임스탬프 모두 확인
          aws s3 sync front/dist/pdf/ s3://${{ secrets.S3_BUCKET_NAME }}/pdf/ \
            --delete
          
      - name: Invalidate CloudFront (selective)
        run: |
          # index.html과 주요 파일만 무효화
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/index.html" "/assets/*"